apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-02-15T17:35:25Z"
  generation: 1
  labels:
    app: todo-frontend
  name: todo-frontend
  namespace: default
  resourceVersion: "84234"
  selfLink: /apis/apps/v1/namespaces/default/deployments/todo-frontend
  uid: 3625469a-22ce-471c-aee4-07b1db6b225b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: todo-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-frontend
    spec:
      containers:
      - image: docker.io/rodrigobrim/todo-frontend:0.0.1
        imagePullPolicy: IfNotPresent
        name: todo-frontend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-02-15T17:35:43Z"
    lastUpdateTime: "2021-02-15T17:35:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-02-15T17:35:25Z"
    lastUpdateTime: "2021-02-15T17:35:43Z"
    message: ReplicaSet "todo-frontend-864c4d4889" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
